-- Default config
config = {
    replayability_defaults = {
        esc_m_trader_task_new_tasks_addon_dead_night = false,
        mil_smart_terrain_7_7_freedom_leader_stalker_task_skyfall = true,
        bar_dolg_general_petrenko_stalker_task_hold_the_ground = true,
        cit_killers_merc_trader_stalker_task_no_step_back = true,
        yan_stalker_sakharov_task_brain_game = true,
        zat_a2_stalker_barmen_task_mirage = false,
        jup_b220_trapper_task_big_game = true,
        agr_smart_terrain_1_6_near_2_military_colonel_kovalski_task_enforce_embargo = true,
        esc_m_trader_task_cold_blooded_betrayal = true,
        val_smart_terrain_7_4_bandit_trader_stalker_task_shakedown = true,
        yan_stalker_sakharov_task_stolen_specimen = false,
        trader_pri_a15_mlr_task_blood_stained_coin = false,
        jup_a6_stalker_barmen_task_the_keepsake = false,
        jup_a6_freedom_leader_task_freedom_intel_documents = true,
        guid_zan_stalker_locman_task_pilots_pda = false,
        merc_pri_grifon_mlr_task_monolith_plans = true,

        simulation_task_gambling_with_life = true,
        simulation_task_vengence_amplified = true,

        urgent_orders = true
    },
    auto_assignment_defaults = {
        urgent_orders = true
    }
}

local function replayability_options_factory(section)
    return {id = "repl_" .. section, type = "check", val = 1, def = config.replayability_defaults[section]}
end

op = {
	id = "new_tasks_addon", sh = true, gr = {
		{id = "replayability_title", type = "desc", clr = {200, 200, 255, 200}, text="ui_mcm_new_tasks_addon_replayability_title"},
        replayability_options_factory("esc_m_trader_task_new_tasks_addon_dead_night"),
        replayability_options_factory("mil_smart_terrain_7_7_freedom_leader_stalker_task_skyfall"),
        replayability_options_factory("bar_dolg_general_petrenko_stalker_task_hold_the_ground"),
        replayability_options_factory("cit_killers_merc_trader_stalker_task_no_step_back"),
        replayability_options_factory("yan_stalker_sakharov_task_brain_game"),
        replayability_options_factory("zat_a2_stalker_barmen_task_mirage"),
        replayability_options_factory("jup_b220_trapper_task_big_game"),
        replayability_options_factory("agr_smart_terrain_1_6_near_2_military_colonel_kovalski_task_enforce_embargo"),
        replayability_options_factory("esc_m_trader_task_cold_blooded_betrayal"),
        replayability_options_factory("val_smart_terrain_7_4_bandit_trader_stalker_task_shakedown"),
        replayability_options_factory("yan_stalker_sakharov_task_stolen_specimen"),
        replayability_options_factory("trader_pri_a15_mlr_task_blood_stained_coin"),
        replayability_options_factory("jup_a6_stalker_barmen_task_the_keepsake"),
        replayability_options_factory("jup_a6_freedom_leader_task_freedom_intel_documents"),
        replayability_options_factory("guid_zan_stalker_locman_task_pilots_pda"),
        replayability_options_factory("merc_pri_grifon_mlr_task_monolith_plans"),

        replayability_options_factory("simulation_task_gambling_with_life"),
        replayability_options_factory("simulation_task_vengence_amplified"),
        -- Exception for Urgent Orders
        {id = "repl_urgent_orders", type = "check", val = 1, def = config.replayability_defaults.urgent_orders},
        {id = "divider", type = "line"},
        {id = "auto_assignment_title", type = "desc", clr = {200, 200, 255, 200}, text="ui_mcm_new_tasks_addon_auto_assignment_title"},
        {id = "auto_assignment_desc", type = "desc", text="ui_mcm_new_tasks_addon_auto_assignment_desc"},
        {id = "auto_assignment_urgent_orders", type = "check", val = 1, def = config.auto_assignment_defaults.urgent_orders}
	}
}

function on_mcm_load()
    return op
end
