-- TODO: move common or miscellaneous effects here if the don't belong to a specific quest

-- TIP: always use safe_release_manager to take care of corpses that do not belong to squads
-- alife_release tries to remove them through squad function (which ofc fails) and alife():release()
-- might be risky if binders don't get removed properly
local nta_utils = new_tasks_addon_tasks_utils

xr_effects.destroy_with_poltergeist_effect = function (actor, npc, p)
    nta_utils.destroy_with_poltergeist_effect(npc)
end